api:
  host: maximilian-haupt.api2.kubernetes.camp
  podSecurityPolicy: k8scamp-api
  go:
    port: 8080
    replicas: 3
    hpa:
      minReplicas: 1
      maxReplicas: 10
    image:
      name: mxmln/api-go
      tag: 0.0.2

  nodejs:
    port: 3000
    replicas: 3
    hpa:
      minReplicas: 1
      maxReplicas: 10
    image:
      name: mxmln/api-nodejs
      tag: 0.0.7

  redis:
    url: "redis://k8scamp-maximilian-haupt-redis-master:6379"

redis:
  usePassword: false
  nameOverride: maximilian-haupt-redis
  podSecurityPolicy:
    create: true
  rbac:
    create: true
