apiVersion: apps/v1
kind: Deployment
metadata:
  name: api-nodejs
  labels:
    app: api-nodejs
    lang: nodejs
    type: api
spec:
  replicas: 3
  selector:
    matchLabels:
      app: api-nodejs
  template:
    metadata:
      labels:
        app: api-nodejs
    spec:
      containers:
      - name: api
        image: mxmln/api-nodejs:0.0.1
        ports:
        - containerPort: 3000

---

apiVersion: v1
kind: Service
metadata:
  name: api-nodejs
spec:
  selector:
    app: api-nodejs
  ports:
  - protocol: TCP
    port: 80
    targetPort: 3000
