apiVersion: networking.k8s.io/v1beta1
kind: Ingress
metadata:
  name: {{ .Release.Name }}-{{ .Chart.Name }}
  labels:
    type: {{ .Release.Name }}-{{ .Chart.Name }}
  annotations:
    kubernetes.io/ingress.class: "nginx"
    kubernetes.io/tls-acme: "true"
spec:
  tls:
  - hosts:
    - {{ .Values.api.host }}
    secretName: {{ .Release.Name }}-{{ .Chart.Name }}-tls
  rules:
  - host: {{ .Values.api.host }}
    http:
      paths:
      - path: /
        backend:
          serviceName: {{ .Release.Name }}-{{ .Chart.Name }}-nodejs
          servicePort: 80
      - path: /hello
        backend:
          serviceName: {{ .Release.Name }}-{{ .Chart.Name }}-go
          servicePort: 80
