version: "3.2"
services:
    redis:
        image: "redis:alpine"
        command: redis-server /etc/redis/redis.conf
        ports:
            - "6379:6379"
        volumes:
            - ./redis/data:/var/lib/redis
            - ./redis/redis.conf:/etc/redis/redis.conf
    api:
        build:
            context: ./nodejs
            dockerfile: Dockerfile
        ports:
            - "3000:3000"
        environment:
            - REDIS_URL=redis://redis:6379
