apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Release.Name }}-{{ .Chart.Name }}-go
  labels:
    app: {{ .Release.Name }}-{{ .Chart.Name }}-go
spec:
  replicas: {{ .Values.api.go.replicas }}
  selector:
    matchLabels:
      app: {{ .Release.Name }}-{{ .Chart.Name }}-go
  template:
    metadata:
      labels:
        app: {{ .Release.Name }}-{{ .Chart.Name }}-go
    spec:
      containers:
      - name: api
        image: {{ .Values.api.go.image.name }}:{{ .Values.api.go.image.tag }}
        ports:
        - containerPort: {{ .Values.api.go.port }}

---

apiVersion: v1
kind: Service
metadata:
  name: {{ .Release.Name }}-{{ .Chart.Name }}-go
spec:
  selector:
    app: {{ .Release.Name }}-{{ .Chart.Name }}-go
  ports:
  - protocol: TCP
    port: 80
    targetPort: {{ .Values.api.go.port }}
