{
 "title": "Certificates",
 "time": { "from": "now-6h", "to": "now" },
 "panels": [
  {
   "title": "Expiration within 7 days",
   "type": "singlestat",
   "gridPos": { "h": 2, "w": 8, "x": 0, "y": 0 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "count(cert_exporter_secret_expires_in_seconds <= 604800) OR on() vector(0)"
    }
   ]
  },
  {
   "title": "Expiration within a month",
   "type": "singlestat",
   "gridPos": { "h": 2, "w": 8, "x": 8, "y": 0 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "count(cert_exporter_secret_expires_in_seconds <= 4*604800) OR on() vector(0)"
    }
   ]
  },
  {
   "title": "Expiration after one month",
   "type": "singlestat",
   "gridPos": { "h": 2, "w": 8, "x": 16, "y": 0 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "count(cert_exporter_secret_expires_in_seconds > 4*604800) OR on() vector(0)"
    }
   ]
  },
  {
   "title": "Cert Manager Certificate Expiry",
   "type": "table",
   "gridPos": { "h": 12, "w": 24, "x": 0, "y": 2 },
   "targets": [
    {
     "expr": "cert_exporter_secret_expires_in_seconds"
    }
   ]
  }
 ]
}